### ISSUE TITLE
If an api call is un authorized, what should be done?

### ISSUE THREAD

**Issue by tareq89** [NerdCats/WebCat#100]
***Background***
Sometimes, after opening the webcat, it is found that the access token is saved on the browser's local storage, but its validity has ended. In that case, the authorized api calls return unauthorized 401 error.
How that should be handled in the WebCat?

Even after login out and in once more, the api calls returns unauthorized until a full page refresh!

**Comment by tareq89** [comment]
#105

**Comment by faisalgobd** [comment]
#34
