### ISSUE TITLE
Home page Track your order need to be hooked up with job tracking page

### ISSUE THREAD

**Issue by tareq89** [NerdCats/WebCat#102]

**Comment by faisalgobd** [comment]
**Clicking empty `Track Your Order` button should return a error message.**
<img width="755" alt="screen shot 2016-07-24 at 7 53 04 pm" src="https://cloud.githubusercontent.com/assets/17807409/17084194/e31b8586-51d9-11e6-9431-c388a4ce0560.png">
**Should Return an error message like this:**
<img width="540" alt="screen shot 2016-07-24 at 7 51 54 pm" src="https://cloud.githubusercontent.com/assets/17807409/17084200/f50846ee-51d9-11e6-88e3-dc925ad37e4a.png">

**Comment by tareq89** [comment]
done
