### ISSUE TITLE
Authentication/Login mechanism on webcat

### ISSUE THREAD

**Issue by tareq89** [NerdCats/WebCat#11]

**Comment by tareq89** [comment]
Reading this!

https://medium.com/@blacksonic86/authentication-in-angular-2-958052c64492#.mvgskxyql

**Comment by thehoneymad** [comment]
Okay, you'd need to extend http class to write the interceptor later.

**Comment by thehoneymad** [comment]
Create a Pull Request before you merge this. There are a couple of issues that are needed to discuss.

**Comment by thehoneymad** [comment]
@tareq Ive segregated the secured http service here in #32 . Dont cover that work in this ticket.

**Comment by tareq89** [comment]
alright!

**Comment by tareq89** [comment]
Sure vai!

-----Original Message-----
