### ISSUE TITLE
Locality field on User registration form doesn't work, if and only if all the other fields are filled up and then tried locality field

### ISSUE THREAD

**Issue by tareq89** [NerdCats/WebCat#26]
This is interesting, if I randomly fill up the user registration fields, then the locality auto-complete works.
But if we first fill up all the fields and then try to fill the locality autocomplete, then it does not work anymore.

On the browser console, it shows the following error:
http://imgur.com/KXLQGgY

**Comment by thehoneymad** [comment]
We would look into this, can you do this once?

1. do a git clean -dfx
2. do a clean pull origin master
3. keep node to LTS
4. and try a clean build

And check whether the problem persists or not

**Comment by thehoneymad** [comment]
Reproduced the bug, its a bug from Bootstrap typeahead component. Please replace this one with a proper autocomplete control
