### ISSUE TITLE
Restricting access to pages after obtaining access token

### ISSUE THREAD

**Issue by tareq89** [NerdCats/WebCat#34]
**Background:**
Once we obtain the access token after the user logged in, we need to use that access token to restrict user on navigating a page. May be whether the access token is available on the localstorage, based on that, we decide whether the user is logged in or not and let him access other pages.

**Comment by tareq89** [comment]
LoggedInRouterOutlet class mentioned in this article can be a good way to do this: https://medium.com/@blacksonic86/authentication-in-angular-2-958052c64492#.47gyvyefw

**Comment by tareq89** [comment]
I would start working on it once issue #32 is merged with master

**Comment by thehoneymad** [comment]
Please look at #38 too as some of the work might overlap
