### ISSUE TITLE
Create Order Creation Form UI

### ISSUE THREAD

**Issue by tareq89** [NerdCats/WebCat#36]
**Background:**
User needs a form to create the delivery order.

**Comment by thehoneymad** [comment]
Keep the ui/ux label out of everything except ui/ux modification, this is a component work, not ui/ux work

**Comment by thehoneymad** [comment]
Is this a clone of #12 ?

**Comment by tareq89** [comment]
yes, looks like duplicate issue!

**Comment by thehoneymad** [comment]
Kindly progress either one of these and close the other
