### ISSUE TITLE
Migrate WebCat into the new router library of Angular 2

### ISSUE THREAD

**Issue by thehoneymad** [NerdCats/WebCat#57]

**Comment by thehoneymad** [comment]
Not needed now, closing

**Comment by tareq89** [comment]
Should we update it now? if not then why?

**Comment by thehoneymad** [comment]
Angular2 is on rc3. We use a couple of libraries that are not compatible with it. We can make them compatible, but not important now to be honest.

**Comment by tareq89** [comment]
Alright

**Comment by thehoneymad** [comment]
We are using rc1 by the way, when the new router will go to beta from alpha and we would have time to move our ng2-bs3 modal component to rc3 (if no one does it), we'll do it. 

It works now, don't break it.
