### ISSUE TITLE
On enterprise order creation, along with product details, they need a field to include their delivery charge

### ISSUE THREAD

**Issue by tareq89** [NerdCats/WebCat#66]
Background:

X o Y company is our enterprise customer. When they will create an order, they will add the product name, price quantity etc. But along with that, they have their delivery charge.

When we delivered the product to the customers, we charge them what zuumzuum invoices charge them.

And we have our invoice to the customer, where we mention the product details.

Now, imagine the scenario,

In Zuumzuum's invoice:

1. item name: Blue Shirt ,price : 1000 BDT
2. item name: Red Shirt ,price : 1200 BDT
delivery charge : 50 BDT
Total : 2250 BDT

But when Zuumzuum creating order through WebCat, they gave us,

1. item name: Blue Shirt ,price : 1000 BDT
2. item name: Red Shirt ,price : 1200 BDT
given the information, when we generate the invoice, it looks like,

1. item name: Blue Shirt ,price : 1000 BDT
2. item name: Red Shirt ,price : 1200 BDT
Total : 2200BDT

we can see Zuumzuum's 50 taka Delivery charge is missing here. We know we have a service charge field in the order model. I am not sure, whether we let Zuumzuum use that ServiceCharge field, or we use that ServiceCharge field.

Again, if we add this service charge field, then we no longer can provide a generic order creation form for both B2B and B2C. B2C doesn't have a service charge on their own!

**Comment by thehoneymad** [comment]
Nobody has a service charge of their own, that's ours to calculate. If this is the way fetch works now, it has to change. And that's ours to change. 

Our invoice should've only had the delivery charge, nothing else. Whats the point of mentioning my vendors invoice matters there without the service charge in our invoice?

Is that our product, what does that invoice stands for?

**Comment by tareq89** [comment]
Our current invoices looks like this:

Enterprise User's Invoice:
![whatsapp-image-20160621](https://cloud.githubusercontent.com/assets/4245521/16220632/ce431f82-37af-11e6-9f95-8f7a2ffcbffa.jpg)

Our Invoice generated from the System:
![asdasdasdasdasdasdasdasdasdasd](https://cloud.githubusercontent.com/assets/4245521/16220653/f4668a96-37af-11e6-9ce8-59071f7aaf35.PNG)


Both the invoices are delivered to end customers. the service charge field is for our use and zuumzuum will pay it to us, not the end user.

so, now in zuumzuum invoice, they said the total price is X BDT (X=total item price + delivery charge)
in our invoice (for the user), we say total price is X-50 BDT (X-50 = total item price)

**Comment by thehoneymad** [comment]
That's essentially wrong. ZuumZuum's invoice is generated based on their system which handles the delivery charges too. Just because we are doing it now this way doesn't mean the system should be like this. 

If we are exposing fields for service charge, it should be the same service charge field that is exposed to us.

The workflow that should work;
1. Create an order in webcat.
2. To generate an invoice you need t-rex to do that, before doing that, update the service charge field.
3. Generate the invoice and youd have new service charge in our invoice too.

If we end up exposing the service charge fields to ZuumZuum it should be the same service charge field. Opening ambiguous fields which does basically the same thing is harmful for a system design. Unless we need it, we shouldn't do it.

**Comment by thehoneymad** [comment]
And if ZuumZuum is paying the service charge to us, that should work on a different mechanism from TaskCat, it should not and should not be done like this. Open a issue there as that is appropriate thing to do. Plus, these two examples doesn't represent the same job. 

If zuum zuum is paying us 50 taka per job then this doesn't concern the order. It concerns us when the job is post processed. Hope you understand what I'm saying.

**Comment by tareq89** [comment]
1. As far as I am concerned, at the end of the day, the ops creates a report for how many zuumzuum delivery has been done/returned, based on that, the accounts calculates how much money zuumzuum owes us .
2. When we do the B2C orders, then this service charge field is to be updated by us.
3. Clearly I can see, service charge field is simple in case of B2C orders, but bit complicated in case of B2C.

4. Should I expose the service charge field on vendor dashboard we are working on now?
since you said, 

> If we end up exposing the service charge fields to ZuumZuum it should be the same service charge field.

**Comment by thehoneymad** [comment]
No, not right now of course, we should stay on the course we are working on right now and deal with this one eventually. But right now, we need to deliver what we promised.
