### ISSUE TITLE
Reloading page takes to temporarily unavailable page.

### ISSUE THREAD

**Issue by faisalgobd** [NerdCats/WebCat#90]
Steps:
1. Go to http://webcatdevel.azurewebsites.net
2. Reload page.

**Comment by thehoneymad** [comment]
All tests should and always be done against a new master branch unless we are doing a release testing.

**Comment by tareq89** [comment]
this is related to #22 right?

**Comment by thehoneymad** [comment]
Yes. The latest master uses a hashlocation strategy. Taskcatdev is not the latest master
